language: python
python:
  - "3.4"
services:
  - postgres
install:
  - pip install -rrequirements.txt
  - pip install psycopg2 coverage
before_script:
  - cp findeco/tests/local_settings.py.postgrestest findeco/local_settings.py
  - psql -c 'create database findeco;' -U postgres
  - python manage.py migrate
  - python manage.py compilemessages
script:
  - coverage run --source='.' manage.py test findeco node_storage microblogging
  - coveralls

branches:
  only:
    - master
    - feature/django18py3  # todo: remove after travis works
    - develop
    - /^release.*$/
notifications:
  email:
    - jonny@pinae.net
    - qwlouse@gmail.com
